name: fullserva
description: "Digital Agenda"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  google_fonts: ^6.1.0
  uuid: 4.2.2
  table_calendar: ^3.0.9
  intl: ^0.18.1
  provider: ^6.1.1
  mask_text_input_formatter: ^2.7.0
  fl_chart: ^0.66.0
  collection: ^1.18.0
  time_range_picker: ^2.2.0
  flutter_datetime_picker_plus: ^2.1.0
  shared_preferences: ^2.2.2
  currency_text_input_formatter: ^2.1.11
  duration_picker: ^1.1.1
  firebase_auth: ^4.19.4
  flutter_web_plugins:
    sdk: flutter
  mailer: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages