// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAODTnJt5d1AHlkKBGr-uoBd0NX-WEnCiE',
    appId: '1:430759493613:web:06f3099028b1a48db5b1e4',
    messagingSenderId: '430759493613',
    projectId: 'fullserva',
    authDomain: 'fullserva.firebaseapp.com',
    storageBucket: 'fullserva.appspot.com',
    measurementId: 'G-KR28GQMD39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvPmItwh1vs7nohE0LwabKRdlrPa67JmY',
    appId: '1:430759493613:android:f429901e1a0aca83b5b1e4',
    messagingSenderId: '430759493613',
    projectId: 'fullserva',
    storageBucket: 'fullserva.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA73kgZSFzZY-6dQ2ZG9G2twz1YosFwo8w',
    appId: '1:430759493613:ios:96c05f3b4d360bc0b5b1e4',
    messagingSenderId: '430759493613',
    projectId: 'fullserva',
    storageBucket: 'fullserva.appspot.com',
    iosBundleId: 'digital.agenda.fullserva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA73kgZSFzZY-6dQ2ZG9G2twz1YosFwo8w',
    appId: '1:430759493613:ios:bf3daadf50d59469b5b1e4',
    messagingSenderId: '430759493613',
    projectId: 'fullserva',
    storageBucket: 'fullserva.appspot.com',
    iosBundleId: 'digital.agenda.fullserva.RunnerTests',
  );
}
